//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumLove.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consent_Record
    {
        public int User_ID { get; set; }
        public string Consent_Ver { get; set; }
        public System.DateTime Consent_Sign_Date { get; set; }
        public System.DateTime Create_Date { get; set; }
    }
}
