//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumLove.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Document_ID { get; set; }
        public string Document_Type { get; set; }
        public string Document_Version { get; set; }
        public string Document_Content { get; set; }
        public System.DateTime Document_Publish_Date { get; set; }
        public Nullable<System.DateTime> Document_Confirm_Date { get; set; }
        public System.DateTime Document_Create_Date { get; set; }
        public string Document_Create_User { get; set; }
        public System.DateTime Document_Update_Date { get; set; }
        public string Document_Update_User { get; set; }
        public short Document_Update_Cnt { get; set; }
    }
}
