//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumLove.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure_Data
    {
        public long Data_ID { get; set; }
        public int Data_User_ID { get; set; }
        public System.DateTime Data_Measure_Time { get; set; }
        public System.DateTime Data_Measure_Period { get; set; }
        public string Data_Measure_City { get; set; }
        public string Data_Measure_District { get; set; }
        public double Data_Height { get; set; }
        public double Data_Weight { get; set; }
        public double Data_Waist { get; set; }
        public double Data_Systolic_Pressure { get; set; }
        public double Data_Diastolic_Pressure { get; set; }
        public byte Data_Heart_Rate { get; set; }
        public Nullable<decimal> Data_BMI { get; set; }
        public System.DateTime Data_Create_Date { get; set; }
        public string Data_Create_User { get; set; }
        public System.DateTime Data_Update_Date { get; set; }
        public string Data_Update_User { get; set; }
        public short Data_Update_Cnt { get; set; }
    
        public virtual UI_User UI_User { get; set; }
    }
}
