//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumLove.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BE_User> BE_User { get; set; }
        public virtual DbSet<Consent_Record> Consent_Record { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Measure_Data> Measure_Data { get; set; }
        public virtual DbSet<UI_User> UI_User { get; set; }
        public virtual DbSet<Token_Record> Token_Record { get; set; }
    }
}
