//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumLove.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UI_User()
        {
            this.Measure_Data = new HashSet<Measure_Data>();
        }
    
        public int User_ID { get; set; }
        public string User_ibon_ID { get; set; }
        public string User_ibon_Name { get; set; }
        public Nullable<System.DateTime> User_Birthdate { get; set; }
        public Nullable<bool> User_Gender { get; set; }
        public string Consent_Ver { get; set; }
        public System.DateTime User_Create_Date { get; set; }
        public string User_Create_User { get; set; }
        public System.DateTime User_Update_Date { get; set; }
        public string User_Update_User { get; set; }
        public short User_Update_Cnt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measure_Data> Measure_Data { get; set; }
    }
}
